# Generated by Django 4.1.3 on 2022-11-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallmart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
    ]
